- module/actor/actor-sheet.js
- module/actor/actor.js
- module/cairn.js
- module/item/item-sheet.js
- module/item/item.js
- package-lock.json
- package.json
Adds the standard js package to the project for the purpose of linting files. This allows everyone to be using a consistent style with sensible defaults that is popular in the javascript community. Hopefully this can allow the project to get the best of both worlds of a unified style but also minimal bikeshedding
> Add standardjs library and lint existing files

- css/cairn.css
- module/item/item-sheet.js
> Fix some small visual issues

- module/actor/actor-sheet.js
- templates/actor/character-sheet.html
https://user-images.githubusercontent.com/4121835/118378067-61e32300-b5d1-11eb-8aac-7f26aa184971.mp4
> Toggle item descriptions on click

- css/cairn.css
- module/actor/actor.js
- template.json
- templates/actor/container-sheet.html
Adds a new actor type for containers--useful for anything you put items in (treasure chests, mules, bags of holding).
Also fixed a bug where we were calculating the number of slots taken up by items without regard to how many of the item they were.
> Add containers actor type

- module/actor/actor-sheet.js
- templates/actor/character-sheet.html
- templates/actor/npc-sheet.html
- templates/item/item-sheet.html
- templates/item/weapon-sheet.html
- Resolves #18 
- Fixes a minor bug where clicking on the Items list header causes a console error (see video below):
https://user-images.githubusercontent.com/18514520/130633089-4fda4be4-97fd-464a-a9e7-549ffa9a070f.mp4
> Add critical dmg tag

- module/actor/actor.js
- module/cairn.js
Resolves Issue #42 
Updated CairnActor to fix v0.9 Item Methods
* CairnActor now extends documentClass Actor.
* Updated deleteOwnedItem, now no longer an override
* Added createOwnedItem
* Added getOwnedItem
> Issue 42 - Fixed Actor Sheet Item Methods

- module/actor/actor.js
Hotfixes #42 
Fixed deleteOwnedItem method
* Now using the appropriate update and delete methods on item document.
> Issue 42 - Hotfix; Using appropriate Item Document Methods

- css/cairn.css
- templates/actor/character-sheet.html
Fix CSS for tabs. It now looks like this:
> Fix tabs CSS

- lang/da.json
- lang/en.json
- lang/fr.json
Update some translations keys for compatibility with Foundry VTT v11.
> Update translation keys for Foundry VTT v11

- module/damage.js
> fix: damage apply

- templates/item/item-sheet.html
- templates/parts/items-list.html
> fix: weightless item actions

- css/cairn.css
- lang/cn.json
- lang/da.json
- lang/de.json
- lang/en.json
- lang/fr.json
- lang/pt-BR.json
- template.json
- templates/item/armor-sheet.html
- templates/item/item-sheet.html
- templates/item/spellbook-sheet.html
- templates/item/weapon-sheet.html
closes #81 
Added item cost attribute.
> feat: item cost

- module/utils.js
> fix: multiple weapons roll

- css/cairn.css
- lang/en.json
- lang/pl.json
- module/actor/actor-sheet.js
- module/actor/actor.js
- module/cairn.js
- module/settings.js
- template.json
- templates/actor/character-sheet.html
- templates/parts/items-list.html
Closes #108 
Player character panic state.
> feat: character panic feature

- css/cairn.css
- templates/item/armor-sheet.html
- templates/item/weapon-sheet.html
Closes #109 
Weightless armor and weapons.
> fix: weightless weapon and armor

- module/actor/actor-sheet.js
- module/cairn.js
- templates/item/armor-sheet.html
- templates/item/item-sheet.html
- templates/item/object-sheet.html
- templates/item/weapon-sheet.html
> fix: hide uses for weightless items

- lang/cn.json
- lang/da.json
- lang/de.json
- lang/en.json
- lang/es.json
- lang/fr.json
- lang/pl.json
- lang/pt-BR.json
- templates/actor/npc-sheet.html
> fixed npc sheet

- module/actor/actor.js
- system.json
> checking abilities existence in roll data

- .gitignore
- lang/en.json
- lang/pl.json
- module/cairn.js
- module/item/item.js
> fix: available uses visualization

- lang/en.json
- lang/pl.json
- module/actor/actor-sheet.js
- module/actor/actor.js
- module/item/item.js
- module/settings.js
- module/utils.js
- templates/parts/items-list.html
Small improvements:
- optional item type icons in inventory
- optional Cairn dice notation in rolls
- item/container delete confirmation
> Small improvements

- lang/en.json
- lang/pl.json
- module/actor/actor-sheet.js
- module/actor/actor.js
- module/item/item.js
- module/settings.js
- template.json
- templates/item/spellbook-sheet.html
- fixed item quantity computations and management
- visibility of regenerate button in charsheet header is configurable
> more fixes

- module/actor/actor-sheet.js
- module/utils.js
> fix: drag items from compendium

- lang/en.json
- lang/pl.json
- module/actor/actor-sheet.js
- templates/parts/items-list.html
Cleaned up "petty" and "quantity" representation.
> cleaned up petty and quantity

- module/actor/actor-sheet.js
- module/actor/actor.js
- templates/dialog/add-item-dialog.html
Add petty items even if inventory is full
closes #132
> fix: add petty items

- module/actor/actor-sheet.js
- templates/actor/character-sheet.html
> enriched character description and notes

- css/cairn.css
- lang/en.json
- lang/pl.json
- module/actor/actor-sheet.js
- module/actor/actor.js
- module/cairn.js
- module/settings.js
- template.json
- templates/actor/character-sheet.html
- templates/dialog/add-feature-dialog.html
- templates/parts/feature-list.html
- refined item action buttons
- features - additional character traits with mechanical effect - initial implementation
> feature list

- lang/en.json
- lang/pl.json
- module/actor/actor-sheet.js
- module/actor/actor.js
- module/settings.js
- templates/actor/character-sheet.html
- templates/actor/npc-sheet.html
- templates/dialog/set-equipment-limit-dialog.html
fixes #136 
- Added option for character equipment limit
> feat: character equip limit
